apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3-typhoon
  namespace: free5gc
  labels:
    app.kubernetes.io/component: iperf3
    app.kubernetes.io/part-of: 5gcityverse
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: iperf3-client
          image: networkstatic/iperf3:latest
          imagePullPolicy: IfNotPresent
          command: ["iperf3", "-c", "iperf3-server.free5gc.svc.cluster.local", "-u", "-b", "5M", "-t", "120", "-l", "60", "--trip-times", "--json"]
